### ISSUE TITLE
finish setting up python-social-auth

### ISSUE THREAD

**Issue by alee** [comses/miracle#1]
http://python-social-auth.readthedocs.org/en/latest/configuration/settings.html

**Comment by alee** [comment]
Hey Calvin, any interest in working on this? It'd be nice to offer automatic account creation and authentication via FB/Google/Twitter/GitHub/etc so users don't have to remember Yet Another Password. Should also check if researchgate and academia.edu offer external auth services.

**Comment by cpritcha** [comment]
I'd love to work on that. I will look at the documentation and figure it out.
