### ISSUE TITLE
Dependencies - What can we get rid of?

### ISSUE THREAD

**Issue by cpritcha** [comses/miracle#13]

**Comment by cpritcha** [comment]
## Low hanging fruit

*pytest* - not used anywhere

*pyunpack, patool* - if we were willing to have only zip file archive uploads (instead of .7z, .bzip2 etcetera). That would require some refactoring and adding a zip file extraction package as a dependency.

**Comment by warmdev** [comment]
We should have 7z. For csv files the compressed file can be much smaller than zip.

**Comment by alee** [comment]
Can we replace pyunpack with just patool?

**Comment by cpritcha** [comment]
We could get rid of `pyunpack` but we would have to wrap `patool`.  The `pyunpack` package hasn't been updated in a while (~2 years) but it is really short (a few hundred lines) and it wouldn't be too hard to change if we need to.

**Comment by alee** [comment]
the `hachoir*` packages are screwing up my django shell (which I use a ton to interact with the DB sometimes and do one-offs during development). It looks like they are only needed for the MP4Loader, which isn't essential. Is this removable?

**Comment by cpritcha** [comment]
`hachoir` is only needed for the MP4Loader. It is removable.
