### ISSUE TITLE
document docker deployment and management

### ISSUE THREAD

**Issue by alee** [comses/miracle#18]
Need docs for both prod and dev deployments.

Upgrading containers
- http://stackoverflow.com/questions/26734402/how-to-upgrade-docker-container-after-its-image-changed
- how to handle app updates and django DB migrations?

**Comment by warmdev** [comment]
I think this involves:
* Requirements
    - Strict separation of apps and data as suggested in the link (which we have been doing)
    - Separate the `miracle` app itself and the deployment scripts (Dockerfiles and scripts) into separate repositories. This is not necessary but cleaner in my opinion. Then the `miracle` Dockerfile pulls the `miracle` app from its GitHub repo. 
    - The startup script (`CMD`) in the `miracle` Dockerfile would perform migrations and static file collections (something like https://github.com/warmdev/miracle-docker/blob/master/miracle.sh but can be more complex as required)
* Update procedure
    - Update Dockerfiles (for example to use newer versions of Java or DeployR) 
    - Prepare databases (sometimes newer versions of apps may require the databases be upgraded using special scripts or instructions)
    - Force rebuild all images (there is no such command available at the moment I think, see https://github.com/docker/docker/issues/1326. What we can do is to simply add or remove a space from the first line of the Dockerfile which will force it to rebuild)
    - Take down the website, stop the containers, and start the containers using new images in the right order

**Comment by warmdev** [comment]
Update: It is possible to force rebuild an image without cache using the `--no-cahe=true` flag. However this will rebuild the entire image from start. If we only want to rebuild from a certain line, use the blank space method as mentioned above.
