### ISSUE TITLE
split docker images into separate repositories

### ISSUE THREAD

**Issue by alee** [comses/miracle#21]
Can still include them as [submodules](http://git-scm.com/docs/git-submodule) in the miracle repo with docker-compose but I think I agree with @warmdev that it's cleaner if they are in their own repo. @cpritcha want to work on this sometime after CCS '15 is over?

Discussion welcome though if you think it's still better to keep them tightly coupled.

**Comment by cpritcha** [comment]
Submodules sound good with me. I think we should have a new repo then with the docker compose file and any deployment and system administration (database and file system backup code) associated tasks there. Then the django webserver, deployr and radiant would be submodules.

**Comment by cpritcha** [comment]
I think that some things are difficult to split apart though. It would be hard to test deployr and radiant separately because we need the code to process and extract the relevant project information.
