### ISSUE TITLE
demo workflow

### ISSUE THREAD

**Issue by alee** [comses/miracle#33]
0. Create a new project, set project short name or use auto-assigned one
1. Upload a project archive (briefly introduce project archive requirements: folder layout, `packrat` tool)
2. Annotate data columns (brief introduction of backend grouping process)
3. Annotate scripts (automatically pull metadata from script: parameters, package dependency, source dependency), view scripts content, download scripts
4. Execute analysis with parameters, view results, shares, comments, etc.
5. Publish project
6. Navigate to other projects (view comments, activity stream, etc)
7. Admin functions (activate scripts, delete comments, etc)

**Comment by warmdev** [comment]
0. Create a new project on MIRACLE and get the project short name 
1. Upload a project archive (brief introduction of the requirements for project archive: folder layout, `packrat` tool)
2. User annotates data columns (brief introduction of backend grouping process)
3. User annotates scripts (automatically pull metadata from script: parameters, package dependency, source dependency), views scripts content, downloads scripts
4. User executes analysis with parameters, views results, shares, comments, etc.
5. User publishes project
6. User navigates other projects (view comments, activity stream, etc)
7. Admin functions (activate scripts, delete comments, etc)
