### ISSUE TITLE
jQuery and Bootstrap load order

### ISSUE THREAD

**Issue by cpritcha** [comses/miracle#38]
When I view the website under Nginx I get a Javascript error

```
TypeError: $(...).modal is not a function
```

This results in the Projects list not being displayed in the Dashboard page

**Comment by alee** [comment]
I haven't been able to reproduce this in production or anywhere else, ok to close this Calvin? I think this is probably an artifact of your deployment.

That said, there are a number of issues we really need to fix for prod deployment, especially related to permissions + UID management (nginx user <-> celery user <-> uwsgi / django user). Let's discuss at our next meeting.
