### ISSUE TITLE
metadata extraction: set DataColumn.data_type to appropriate DataType

### ISSUE THREAD

**Issue by alee** [comses/miracle#46]
DataColumn.data_type is currently being assigned Real for any real number by `analyzer.py`. The data model currently tries to distinguish between integer and floating point numbers - can you try to set those properly? 

http://stackoverflow.com/questions/4541155/check-if-a-number-is-int-or-float may be useful

Currently the list of DataColumn DataTypes is:

bigint (integer)
boolean
decimal (float)
text (string)

We can adjust this list as needed.. Thoughts?

**Comment by cpritcha** [comment]
Sure. I'll change the data types.

**Comment by cpritcha** [comment]
Should be fixed now

**Comment by alee** [comment]
Things like agent_id in the luxedemo example should be classified as an integer, as well as many of the variables in the runLog data group (runID, random, runNumber, msgOutLevel, worldx, worldy, etc. It looks like they all get thrown into the decimal / float bucket though.

**Comment by cpritcha** [comment]
When I look at the luxe example I imported I *agent_id*, *runID*, *msgOutLevel*, *worldx* and *worldy* are all classified as `bigint`s. Could you run the unit tests and see if the *test_guess_type* test succeeds?

**Comment by cpritcha** [comment]
I've put up some changes that definitely improve the parsing of `decimal` and `bigint` types but couldn't find replicate the misclassification of the columns you mention (`runID`, `random`, `runNumber` etc). If these changes do not help maybe you could take a look at the locale settings? Mine are

```python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
(None, None)
```

**Comment by alee** [comment]
I thought I'd commented on this already but I think this is only an issue on my Arch dev box that is running gdal 2.0.x with Python 3 by default. I'll test this out on production very soon and close if it's working there.
