### ISSUE TITLE
look into async file uploaders

### ISSUE THREAD

**Issue by alee** [comses/miracle#5]
Django file upload handling: https://docs.djangoproject.com/en/1.8/topics/http/file-uploads/

Client-side options that we may want to provide integration with:

- http://fineuploader.com/index.html (free for OSS)
- http://www.plupload.com/
- https://github.com/blueimp/jQuery-File-Upload

**Comment by alee** [comment]
Hey Calvin, feel free to reassign back if you'd like to punt back on this

**Comment by cpritcha** [comment]
Sounds good. I'll work on getting file uploads working.

**Comment by cpritcha** [comment]
An alternative Dropzone.js (http://www.dropzonejs.com/)

https://github.com/amatellanes/dropzonejs-django-file-upload

**Comment by alee** [comment]
Added Dropzone in https://github.com/comses/miracle/pull/7
