### ISSUE TITLE
If one script fails to run, cannot run another script without refreshing the page first

### ISSUE THREAD

**Issue by warmdev** [comses/miracle#69]
Error message: Analysis already running, please wait until it has completed.

After refreshing the page, the second script runs without problem.

**Comment by alee** [comment]
Can you provide details on how to reproduce this?

**Comment by warmdev** [comment]
To reproduce this, run script `Figure 1` with input `sdb=31` (the possible values are 0/10/20/30/40/50) so this is going to fail. After the `failed` status appears, try run the script again with any input parameter, and you will see the error message.
