### ISSUE TITLE
Stress test the demo server

### ISSUE THREAD

**Issue by warmdev** [comses/miracle#75]
This is important if we are going to serve 30 or more concurrent users. Mainly,

- [ ] Responsiveness of the Radiant app with many concurrent users
- [ ] Performance of the DeployR server with many concurrent script run requests (execution time, RAM requirements, CPU usage)

**Comment by alee** [comment]
Can use http://locust.io/ or apache ab to do something simple - agreed, we should figure out the max number of supportable users N. We may need to structure the workshop to have < N participants looking at the app at a time..?

**Comment by alee** [comment]
radiant becomes a clear bottleneck with over 2-3 concurrent users, and I'm guessing DeployR would also be an issue there. need to revisit that part of the architecture

**Comment by warmdev** [comment]
The problem with Radiant is that Shiny Server open source edition is single-threaded, so that can only be solved by one container per user. For DeployR, we can do one or more containers per-project based on load.

BTW Docker 1.12 introduced a swarm mode which makes scaling a lot easier, and I assume it will come to dockerpy soon.
