### ISSUE TITLE
upload dataset zips

### ISSUE THREAD

**Issue by alee** [comses/miracle#9]
zipfile with prescribed structure:

- `/data`
- `/scripts`
- anything else?

**Comment by cpritcha** [comment]
What benefits do you see from prescribing a structure on zipfile uploads? 

I can see that file classification may be easier (every file in the `data` folder is of the `Data` type and everything in the `scripts` folder is of the `Code` type) but classification by extension should also handle most of these cases.

**Comment by cpritcha** [comment]
I think that having special filenames could be helpful. A `README` file in the base directory could be turned into the Analysis description or a `requirements.txt` file in the base directory could be classified as a `Configuration` type.

**Comment by alee** [comment]
I could go either way but I think I prefer the template structure because it makes the user think about curating their own data and not throw a pile of files at us and have us try to sort things out. So the main benefits are simplicity and explicitness, and hopefully reduced false positives, especially for overloaded text data, e.g., .txt files can hold CSV/TSV data just fine, but if they live in a /data directory we will interpret them as datasets.

**Comment by alee** [comment]
https://github.com/comses/miracle/wiki/Project-Archive-Preparation-Guidelines
